### PR TITLE
fix: DynamicScroller should pass its own keyField prop to child RecycleScroller

### PR DESCRIPTION
**Pull request by nicooprat**
When using DynamicScroller, the `keyField` prop was ignored because it was manually set as its default value `id` here.

### CODE REVIEW

**Comment by ryanpwaldon** [comment]
Might need to bind the attribute for this one to work 😜

**Comment by ryanpwaldon** [comment]
That was fast. Not banking on a merge anytime soon tho 😆🤞

**Comment by Akryum** [comment]
I merged this PR too fast, it is expected that `DynamicScroller` hard code `key-field` to `id`.

I will revert this to fix #758

**Comment by Akryum** [comment]
Items passed from `DynamicScroller` to `RecycleScroller` are always of the shape `{ id, item, size }`:
https://github.com/Akryum/vue-virtual-scroller/blob/95b934a10343338d102324766e84036e06d9a6a6/packages/vue-virtual-scroller/src/components/DynamicScroller.vue#L115-L125

**Comment by leochen-g** [comment]
This issue has resurfaced in version 2.0, perhaps requiring another round of fixes.

**Pull request merged**
