### PR TITLE
feat: add skipHover prop to deactive the hover detection

### PR DESCRIPTION
**Pull request by gans-groover**

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
Are you sure that this actually fixes the performance issue? IIUC the problem is rerendering the entire list (as opposed to single item) on each hover update and having this prop doesn't avoid it, theoretically.

**Comment by gans-groover** [comment]
hi @Akryum could you please release this change as vue-virtual-scroller@1.0.11 ?

**Comment by ishitatsuyuki** [comment]
Actually nevermind, the condition in event handlers avoids triggering the rerender altogether.

Since this was already merged let's keep skipHover for v1. For v2 we'll see if we still need the same workaround or we can just use the component wrapper to avoid rerender.

**Comment by james-astra** [comment]
Was this released? I cannot access the prop in the latest release on NPM and am having trouble building the source.

**Comment by kemalandic** [comment]
Hi @gans-groover , can you add this prop to the DynamicScroller?

**Pull request merged**
