### PR TITLE
Support scroll parent other than window

### PR DESCRIPTION
**Pull request by simplesmiler**

### CODE REVIEW

**Comment by MatthewAry** [comment]
This is EXACTLY what I needed. Thanks @simplesmiler !

**Comment by MatthewAry** [comment]
It's been a month. @drewjbartlett is there something holding up a merge?

**Comment by drewjbartlett** [comment]
@MatthewAry not sure what you mean :D. Was I supposed to review this?

**Comment by MatthewAry** [comment]
@drewjbartlett 
Well, I don't know how this project is organized or its leadership structure. It looks like you have write access to the project and you were the last person to make a change to the master branch. So I decided to ask. Would you be so kind to review it?

**Comment by drewjbartlett** [comment]
@MatthewAry I actually have only made a PR for the readme haha. I won't have time to take a deep dive into reviewing it. I also cannot merge this PR since I have no permission unfortunately. I think we need @Akryum to have a 👀

**Comment by AGPDev** [comment]
+1 !!!!!1

**Pull request merged**
