### PR TITLE
feat: new `disableTransform` prop to use top/left instead of translate

### PR DESCRIPTION
**Pull request by AousAnwar**
A small change for a particular use case.

The css Transform property create a new scope inside the browser, so the item with fixed position is positioned relatively to the nearest parent with the transform property (.vue-recycle-scroller__item-view) and not the browser itself.

Here I'm adding a "modal" property the the item object, when set to true, it replace "transform (x or y)"  with "left or top" depending on the "direction" also unset the css "will-change" property.

Typical use case : zoom in modal for images or video display

### CODE REVIEW

**Comment by crow7m** [comment]
aby updates on this pull request, might be useful for dynamic scroller as well

**Comment by bobaoapae** [comment]
Hello, can this be merged? I have this issue

**Comment by jhanson409** [comment]
Would really appreciate this getting merged if possible. Seeing this issue.

**Review by louisraetz — APPROVED** [review]

**Comment by Akryum** [comment]
I'm not sure we want to change this as it might degrade performance.

**Pull request merged**
