### PR TITLE
Emit start and end indexes on change

### PR DESCRIPTION
**Pull request by Herteby**
I'm integrating virtual-scroller with Meteor, to fetch items on-demand from the database.

Added features:
- Emit start and end indexes on change
- Support sparse Arrays
- Enable specifying a 'default' renderer, for when an item doesn't have a type, or doesn't exist at all.
- Enable disabling the key field, by setting :keyField="false"

### CODE REVIEW

**Comment by Herteby** [comment]
Maybe it's better to just disable the key field than trying to generate a "backup key" from the index.

**Comment by asafyish** [comment]
I am using Vue developer tools. Will this create noise of many many events ?

**Comment by Herteby** [comment]
Yeah you're right, it does. I could add a prop to toggle it on.

I don't know, is this even a desired feature though, or is this too niche?

**Comment by asafyish** [comment]
Having the ability to fetch rows on scroll,  does sound like something that people would want, maybe it could be implemented differently ?

**Comment by Herteby** [comment]
Events is the only recommended way of doing child -> parent communication in Vue though.

**Comment by Akryum** [comment]
Thanks for your PR! The latest release has a new `emitUpdate` prop.

**Pull request closed without merging**
