### PR TITLE
feat: gridItems prop

### PR DESCRIPTION
**Pull request by okwme**
like a grid of images

### CODE REVIEW

**Comment by Akryum** [comment]
Thank you for your PR! Please don't commit dist files. :smile:

**Comment by ADRDev** [comment]
What's the status on this? I have this use-case.. I've faked it for now (item height = row height/num columns).  But, if the last row doesn't have enough items to fill all columns the height gets cut off.

**Comment by okwme** [comment]
removed dist

**Comment by okwme** [comment]
@ADRDev sounds like should be a new issue if/after the PR gets merged

**Comment by ADRDev** [comment]
@okwme oh, I wasn't saying it was a bug with your fork. i was saying it's the reason why i need your feature pulled in!

Side note: I think when you removed dist the PR includes it (ie. the merge would remove dist in master).

**Comment by Akryum** [comment]
Hi there! You need to make some adjustments for me to merge this. :smile:
Also, it would be great to think about ways to make this happen in variable height mode too.

**Comment by CapitaineToinon** [comment]
Can we get an update on this? I'd love to see this feature being implemented.

**Comment by Heartz66** [comment]
I'm really interested in this feature.

**Comment by nachogarcia** [comment]
No news on this after 2 and a half years? Is it ever going to be supported?

**Comment by Bearfinn** [comment]
Bumped this. This is very interesting and will fit very well with my project. Are there any alternatives while waiting for this to be supported?

**Comment by fgilio** [comment]
> Bumped this. This is very interesting and will fit very well with my project. Are there any alternatives while waiting for this to be supported?

Sure it's late, but for reference: https://github.com/Akryum/vue-virtual-scroller/issues/356

**Comment by Ktar5** [comment]
Would like an update on this

**Comment by utopianknight** [comment]
Is this still being worked on?

**Comment by mateuszdargacz** [comment]
will that be supported?

**Comment by EricRabil** [comment]
It doesn't look like this repo has been getting much attention from the maintainer. Would you guys be interested in a fork that takes in the recent PRs and keeps up with some of the bigger issues?

**Comment by seeratawan01** [comment]
Word Around by dividing the array into chunks: https://github.com/seeratawan01/Virtual-Scroll-Playground/

**Pull request merged**
